server:
  port: 8090

spring:
  application:
    name: Chat-GPT-Conversations
  datasource:
    url: jdbc:postgresql://localhost:5432/kGPT
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

openai_api_key: ${MY_OPENAI_KEY}
